name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/shared

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "chore(release): 📦 version packages"
          title: "chore(release): 📦  version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
